# Module 6 Exercises - Correlation and Models

In [1]:
import pandas as pd
import numpy as np

### Exercise 1:

From the datasets folder, load the "tamiami.csv" file as a dataframe. Rename the columns (in order) to the following:

- location
- sales
- employees
- restaurants
- foodcarts
- price

Then do a correlation table on that dataframe. What features (columns) are correlated? What features aren't correlated?

In [2]:
location = "datasets/tamiami.csv"
df = pd.read_csv(location)
df.columns
df.rename(columns={'Cart Location' : 'location'}, inplace=True)
df

,location,Hot Dog Sales,Employees in Nearby Office Buildings,Num of Nearby Restaurants,Num of Other Food Carts Nearby,Price
0,1,100,1600,8,12,4.16
1,2,80,1200,6,13,4.63
2,3,450,2800,19,6,0.50
3,4,580,4300,19,2,0.47
4,5,100,1400,6,13,4.24
5,6,50,700,4,11,4.21
6,7,120,1600,9,13,3.53
7,8,560,3500,18,2,0.45
8,9,250,1900,15,9,2.10
9,10,290,2400,13,9,1.59
10,11,520,3100,16,3,0.47
11,12,480,2700,18,4,0.53
12,13,510,3200,17,3,0.55
13,14,90,1600,8,16,4.54
14,15,110,1500,7,13,3.60
15,16,210,1600,10,11,2.81
16,17,40,600,2,14,4.99
17,18,180,1800,7,14,2.82
18,19,90,1500,9,14,4.21
19,20,80,1500,7,14,4.29
20,21,190,1900,8,13,3.13
21,22,240,1500,16,16,2.34
22,23,300,2500,15,9,1.61
23,24,260,1500,14,13,1.84
24,25,420,2600,18,6,0.51
25,26,60,900,5,12,4.64
26,27,200,1700,11,12,2.72
27,28,280,1900,10,8,1.79
28,29,500,3000,15,4,0.48
29,30,460,2900,17,5,0.53

### Exercise 2:

Using the dataframe from the previous exercise, choose features (columns) to create a linear regression formula to predict sales. Try it with and without the y-intercept. How does it make a difference? Does adding or removing features in your model formula make a difference in the output?